version: '3.8'
services:
  movies:
    image: vajidshiak/mahimoviess1:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: vajidshaik/mahitrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: vajidshaik/mahidth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: vajidshaik/mahirecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
